# Generated by Django 4.1.5 on 2023-01-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='nos',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
